alias c='clear'
alias h='history'
alias df='df -Th'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls -aCF --color=auto'
alias ll='ls -alF --color=auto'
alias python=python3
alias mongou='mongo -u root -p --authenticationDatabase admin'
export PS1='[\[\e[1;31m\]\u\[\e[m\]@\[\e[1;32m\]\h\[\e[m\] \[\e[1;36m\]\w\[\e[m\]]\$ '