#  ベースイメージの設定 // Base Image
FROM ubuntu:16.04

# Nginx のインストール // Nginx Install
RUN apt-get -y update && apt-get -y upgrade 
RUN apt-get -y install nginx
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf

#  ポート指定 // Port Setup
EXPOSE 80

# Web コンテンツの配置 // Web Content allocation
ONBUILD ADD website.tar /var/www/html/

# Nginx の実行 //Nginx Execution
CMD ["nginx"]
