apiVersion: apps/v1
kind: Deployment
metadata:
  name: weathers
  labels:
    app: weaters
spec:
  replicas: 1 # three pod
  selector:
    matchLabels:
      app: weathers
  template:
    metadata:
      labels:
        app: weathers
    spec:
      containers:
        - name: weathers
          image: daeun1013/weathers
          ports:
            - containerPort: 8000 # Container port(pod port)