apiVersion: apps/v1
kind: Deployment
metadata:
  name: remoteapi
  labels:
    app: remoteapi
spec:
  replicas: 3 # three pod
  selector:
    matchLabels:
      app: remoteapi
  template:
    metadata:
      labels:
        app: remoteapi
    spec:
      containers:
        - name: remoteapi
          image: sy3058/remoteapi
          ports:
            - containerPort: 8000 # Container port(pod port)